# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    # 1. Start at 5:30 AM Sri Lanka (00:00 UTC)
    - cron: '0 0 * * *'
    
    # 2. Restart at 11:30 AM Sri Lanka (06:00 UTC) to avoid the 6h timeout
    - cron: '0 6 * * *'
    
    # 3. Restart at 5:30 PM Sri Lanka (12:00 UTC)
    - cron: '0 12 * * *'
    
    # 4. Final kick-off for the last leg (ends at 11:30 PM Sri Lanka / 18:00 UTC)
    - cron: '0 18 * * *'

  workflow_dispatch: # Manual button for testing

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install



    - name: Start application
      run: npm start
